### ISSUE TITLE
CUIs in stanford_cuis_svd_300.txt

### ISSUE THREAD

**Issue by dmitriydligach** [clinicalml/embeddings#1]
The first column in stanford_cuis_svd_300.txt contains numbers (e.g. 4411984) which don't seem to be CUIs (CUIs typically begin with character 'C'). Is there a way to map these numbers to CUIs?

The first column in DeVine_etal_200.txt does look like it contains legitimate CUIs (e.g. C0030705).

**Comment by dsontag** [comment]
Yes, the mapping is given [here](https://github.com/clinicalml/embeddings/blob/master/eval/2b_concept_ID_to_CUI.txt). You can see an example of it by looking at the code in "eval/visualize_stanford_embeddings.py"

**Comment by dmitriydligach** [comment]
Thanks!
